import React from 'react';

function About() {
    return (
        <div>
            <h1>About</h1>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate beatae impedit iste, perferendis blanditiis tempore odio nulla, maiores quisquam accusamus repellat sint placeat sed veritatis dolor incidunt sequi repudiandae fugit rem consequuntur asperiores. Deserunt quas facilis, maiores voluptatem ad expedita? Ad eum quisquam eos veniam repellendus, inventore modi nemo blanditiis necessitatibus reprehenderit dolore temporibus delectus laboriosam, impedit officia mollitia adipisci? Ad ducimus architecto illum, exercitationem ratione minima atque quae sit vitae vero, sint nostrum est placeat. Cupiditate, quis. Quas incidunt velit reiciendis animi dolore voluptatem beatae, esse, voluptas, doloribus corporis eveniet praesentium. Dolore dicta aperiam blanditiis error! Neque amet quisquam libero nobis, voluptas porro ratione natus possimus quia obcaecati vel, nihil fugiat. Id repellat officia molestiae a, neque quae porro animi corporis ullam quibusdam rerum voluptates error. Ut, quaerat. Temporibus delectus vitae magni? Necessitatibus explicabo reprehenderit voluptatibus quisquam aperiam, similique minus doloremque eveniet maiores, sapiente quod! Quas dolor ipsa blanditiis ut sapiente repellendus consequuntur perspiciatis veritatis esse earum veniam, fuga repellat, obcaecati nisi doloribus provident, cum possimus vel eligendi. Id cum delectus explicabo. Culpa beatae hic ipsa quaerat nobis. Cumque temporibus esse quod quisquam aperiam quasi, consectetur accusantium, exercitationem ea officia adipisci non, dolorem sunt iusto obcaecati quas ducimus explicabo nam eum vel aut repellat ex voluptas! Quae excepturi blanditiis harum dolorum quis laboriosam tempora similique recusandae veritatis architecto non vel fugit quidem at ut a eligendi dolore assumenda earum dicta dolor doloribus, aliquid velit sunt? Repellat eaque quia impedit veritatis consectetur expedita, nemo modi cumque et illum hic praesentium eum! Doloremque dignissimos nulla quasi. Voluptas, nihil obcaecati repellendus harum architecto, consequuntur necessitatibus minus ipsum earum, odio nisi quos exercitationem tempora at quo similique quibusdam sapiente veritatis. Sed mollitia modi illo veniam, dicta in ad alias iusto excepturi magni atque velit ducimus quia officia nemo amet, vitae non tenetur exercitationem!
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit enim soluta, incidunt inventore beatae dolor quisquam reprehenderit sunt quasi quod! Rerum dolore neque non quod aspernatur repellat suscipit odit doloribus alias, quisquam, incidunt praesentium animi tenetur porro est a excepturi beatae quidem molestias consequatur possimus aut officiis! Magnam quisquam eos harum voluptas illo alias vitae quidem saepe veniam impedit perspiciatis aliquid eligendi, in quae rerum magni. Architecto cupiditate iusto blanditiis numquam culpa cumque maiores veniam optio accusantium, natus voluptates! Consequuntur officia enim assumenda nemo inventore illo quam facere aliquam minima voluptates modi quo voluptatem earum illum quos, exercitationem nesciunt totam.
            </p>
        </div>
    )
}

export default About;